sudo: required
language: python
python:
    - 3.4
services:
  - docker
before_install:
  - pip install pyflakes
install:
  - pip install .
script:
  - sh test/build.sh
  - sh test/run.sh
after_script:
  - sh test/cleanup.sh
